import type {Chart,SongPackage,RunResult,InputMode} from '../../../contracts/public-types';
import {Engine} from './Engine';
import {AudioEngine} from '../audio/AudioEngine';
import {InputRouter,type Input} from '../input/InputRouter';
import {Renderer} from '../render/Renderer';
import {state,difficultyNames} from '../app/store';
import {escape,toast} from '../app/ui';
import {saveRun} from '../storage/Database';
export class Session {
 readonly engine:Engine;readonly audio:AudioEngine;renderer:Renderer;runId=crypto.randomUUID();status='LOADING';mode:InputMode;autoplay=false;practice=false;private pausedAt=0;private frame=0;private disposed=false;private done=false;private autoIndex=0;private visibility=()=>{if(document.hidden)this.pause('別の画面に移動したため一時停止しました');};private abort=new AbortController();private wake:WakeLockSentinel|null=null;onResult:(r:RunResult)=>void=()=>{};
 constructor(private root:HTMLElement,readonly pack:SongPackage,readonly chart:Chart,private input:InputRouter,opts:{autoplay?:boolean;practice?:boolean;startMs?:number}={}){this.engine=new Engine(chart,this.runId);this.audio=new AudioEngine(state.settings);this.mode=state.settings.inputMode;this.autoplay=opts.autoplay??false;this.practice=opts.practice??false;this.pausedAt=opts.startMs??0;this.root.innerHTML=`<section class="game-scene ${this.mode==='midi'?'midi-mode':''}" aria-label="演奏画面"><div class="night-tint"></div><div class="game-hud"><div class="song-hud"><span class="eyebrow">${difficultyNames[chart.difficulty]} <span class="mode-tag">${this.autoplay?'AUTO':this.practice?'練習':this.mode==='midi'?'電子ドラム':'演奏'}</span></span><h1>${escape(pack.manifest.title)}</h1><small>${escape(pack.manifest.artist)}</small></div><div class="score-hud"><small>スコア</small><strong id="score">0000000</strong></div><div class="combo-hud"><strong id="combo">0</strong><small>コンボ</small></div><div class="gauge-hud"><small>お祭りゲージ <b id="gauge-text">0%</b></small><div class="gauge-track"><i id="gauge-fill"></i><em></em></div><span>クリア 70%</span></div><button class="pause-button" aria-label="一時停止">Ⅱ</button></div><div class="song-progress"><i></i></div><div class="game-stage"><div class="character"></div><div class="stage-message"><span class="eyebrow">CHACHAMARU RHYTHM FESTIVAL</span><strong id="stage-text">さあ、お祭りをはじめよう</strong><small id="fast-late"></small></div><div class="friends"></div></div><div class="pads" aria-label="太鼓の打面"><button class="pad ka" data-pad="ka"><span>カッ</span><small>D · 左のふち</small></button><button class="pad don" data-pad="don"><span>ドン</span><small>F · 左の面</small></button><button class="pad don" data-pad="don"><span>ドン</span><small>J · 右の面</small></button><button class="pad ka" data-pad="ka"><span>カッ</span><small>K · 右のふち</small></button></div><div class="midi-hint">スネア = ドン　 /　 フロアタム = カッ</div><div class="play-overlay"><div class="play-dialog"><span class="eyebrow">準備しています</span><h2>曲を読み込み中…</h2></div></div><button class="rotate-hint">横向きにすると、もっと遊びやすくなります ×</button></section>`;
 const scene=root.querySelector<HTMLElement>('.game-scene')!;this.renderer=new Renderer(scene,scene.querySelector('.game-stage')!,chart,pack.manifest,state.settings);this.root.querySelector('.pause-button')!.addEventListener('click',()=>this.pause(),{signal:this.abort.signal});this.root.querySelector('.rotate-hint')!.addEventListener('click',e=>(e.currentTarget as HTMLElement).remove(),{signal:this.abort.signal});this.input.onHit=i=>this.hit(i);this.input.onPause=()=>this.pause();this.audio.onSuspend(()=>this.pause('音声が停止したため一時停止しました'));document.addEventListener('visibilitychange',this.visibility);this.root.addEventListener('webglcontextlost',e=>{e.preventDefault();this.pause('描画を再開するには曲一覧から読み直してください');},{signal:this.abort.signal});}
 async init(){await this.renderer.init();if(this.disposed)return;this.status='READY';this.overlay('準備はいい？','大きな音符も1回でOK。音に合わせて、ドンとカッ！','演奏をはじめる',()=>void this.start());this.drawFrame();}
 private overlay(title:string,body:string,label:string,action:()=>void,paused=false){const overlay=this.root.querySelector<HTMLElement>('.play-overlay')!;overlay.hidden=false;overlay.innerHTML=`<div class="play-dialog"><span class="eyebrow">${paused?'ひとやすみ':'いっしょに、リズムを刻もう'}</span><h2>${escape(title)}</h2><p>${escape(body)}</p><button class="primary" id="resume-play">${label}</button>${paused?'<div class="pause-options"><label>操作 <select id="pause-mode"><option value="touch">タッチ</option><option value="keyboard">キーボード</option><option value="midi">電子ドラム</option></select></label><a class="button" href="'+escape(location.hash.split('?')[0])+'?retry='+Date.now()+'">最初から</a></div>':''}<a class="text-link" href="#/songs">曲一覧に戻る</a></div>`;overlay.querySelector('#resume-play')!.addEventListener('click',action);const select=overlay.querySelector<HTMLSelectElement>('#pause-mode');if(select){select.value=state.settings.inputMode;select.onchange=()=>{state.settings.inputMode=select.value as InputMode;this.mode='mixed';this.audio.volume();this.root.querySelector('.game-scene')!.classList.toggle('midi-mode',select.value==='midi');};}}
 async start(){try{this.status='LOADING';await this.audio.unlock();if(!this.audio.buffer)await this.audio.load(this.pack.audio);if(this.disposed)return;this.audio.start(this.pausedAt);this.engine.active=false;this.status='COUNT_IN';this.input.clear();this.root.querySelector<HTMLElement>('.play-overlay')!.hidden=true;try{if('wakeLock' in navigator)this.wake=await navigator.wakeLock.request('screen');}catch{/* optional API */}}catch(err){this.status='LOAD_ERROR';this.overlay('曲を再生できませんでした',err instanceof Error?err.message:String(err),'もう一度読み込む',()=>void this.start());}}
 private hit(i:Input){if(!['READY','COUNT_IN','PLAYING','PAUSED'].includes(this.status))return;if(this.status==='PAUSED')return;this.audio.hit(i.color);let t=0;try{t=this.audio.time(i.performanceMs);}catch{this.pause('音声時計を再確認してください');return;}this.renderer.hit(i.color,Math.max(0,t));if(this.status!=='PLAYING'||this.autoplay)return;if(i.source!==state.settings.inputMode){this.mode='mixed';this.root.querySelector('.mode-tag')!.textContent='MIXED';}this.engine.hit({id:i.id,runId:this.runId,color:i.color,inputSongMs:this.audio.time(i.performanceMs-state.settings.inputLagMs),receiptSongMs:this.audio.time(i.receiptMs),deliveryDelayMs:i.receiptMs-i.performanceMs,source:i.source});}
 pause(reason='曲の続きから、2秒のカウントで再開します。'){if(!['PLAYING','COUNT_IN'].includes(this.status))return;try{this.pausedAt=Math.max(this.pausedAt,Math.max(0,this.audio.time()));}catch{/* Keep the last safe position when the clock is unavailable. */}this.engine.active=false;this.status='PAUSED';this.audio.stop();this.input.clear();void this.wake?.release();this.wake=null;this.overlay('ひとやすみ',reason,'つづきから',()=>void this.start(),true);}
 private drawFrame=()=>{if(this.disposed)return;let t=this.pausedAt;if(['PLAYING','COUNT_IN'].includes(this.status)){try{t=this.audio.time();}catch{this.pause('音声時計が停止しました。もう一度再開してください');}}if(this.status==='COUNT_IN'){const left=Math.max(1,Math.ceil((this.pausedAt-t)/1000));this.root.querySelector('#stage-text')!.textContent=String(left);if(t>=this.pausedAt){this.status='PLAYING';this.engine.active=true;this.root.querySelector('#stage-text')!.textContent='音に合わせて、ドン・カッ！';}}
 if(this.status==='PLAYING'){if(this.autoplay){while(this.autoIndex<this.engine.taps.length&&this.engine.taps[this.autoIndex].timeMs+this.chart.offsetMs<=t){const n=this.engine.taps[this.autoIndex++],target=n.timeMs+this.chart.offsetMs;if(target<this.pausedAt&&this.practice)continue;this.engine.hit({id:'auto-'+n.id,runId:this.runId,color:n.color,inputSongMs:target,receiptSongMs:target,source:this.mode});this.audio.hit(n.color);this.renderer.hit(n.color,t);}}this.engine.advance(t);}
 const s=this.engine.snapshot(),events=this.engine.takeEvents();this.renderer.draw(t,s,events);this.root.querySelector('#score')!.textContent=String(s.score).padStart(7,'0');this.root.querySelector('#combo')!.textContent=String(s.combo);this.root.querySelector<HTMLElement>('#gauge-fill')!.style.width=`${s.gauge}%`;this.root.querySelector('#gauge-text')!.textContent=`${Math.round(s.gauge)}%`;
for(const e of events){if(e.kind==='combo'){this.root.querySelector('#stage-text')!.textContent=`${e.value} コンボ！ その調子！`;this.audio.chime(e.value!>=100?3:e.value!>=50?2:1);}if((e.kind==='great'||e.kind==='ok')&&state.settings.fastLate)this.root.querySelector('#fast-late')!.textContent=Math.abs(e.delta??0)<5?'ぴったり！':`${(e.delta??0)<0?'EARLY':'LATE'} ${Math.abs(Math.round(e.delta??0))}ms`;}
if(this.status==='PLAYING'&&t>=this.pack.manifest.durationMs+170&&this.audio.ended&&s.finished&&!this.done)void this.finish();this.frame=requestAnimationFrame(this.drawFrame);};
 private async finish(){this.done=true;this.status='FINISHING';this.engine.active=false;this.audio.stop();await this.wake?.release();const {outcomes:_outcomes,...stats}=this.engine.snapshot();const result:RunResult={runId:this.runId,packId:this.pack.manifest.packId,chartId:this.chart.chartId,audioHash:this.pack.manifest.audio.sha256,chartHash:this.pack.manifest.charts.find(c=>c.chartId===this.chart.chartId)!.sha256,ruleset:'chacha-v1',inputMode:this.mode,autoplay:this.autoplay,practice:this.practice,date:new Date().toISOString(),settings:structuredClone(state.settings),stats,title:this.pack.manifest.title,difficulty:this.chart.difficulty,timingUnstable:stats.timingUnstable};try{await saveRun(result);}catch{toast('結果を保存できませんでした。ストレージ容量を確認してください');}this.status='RESULT';if(!this.disposed)this.onResult(result);}
 showcaseSnapshot(time:number,combo:number){if(!import.meta.env.DEV)return;this.practice=true;this.autoplay=true;this.pausedAt=time;this.status='SHOWCASE';this.engine.active=true;for(const n of this.engine.taps.slice(0,combo))this.engine.hit({id:'fixture-'+n.id,runId:this.runId,color:n.color,inputSongMs:n.timeMs+this.chart.offsetMs,receiptSongMs:n.timeMs+this.chart.offsetMs,source:'keyboard'});this.engine.active=false;this.root.querySelector<HTMLElement>('.play-overlay')!.hidden=true;this.root.querySelector('#stage-text')!.textContent=combo>=100?'100 コンボ！ お祭りは最高潮！':'音に合わせて、ドン・カッ！';}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.abort.abort();document.removeEventListener('visibilitychange',this.visibility);this.input.onHit=()=>{};this.input.onPause=()=>{};this.input.clear();this.audio.dispose();this.renderer.dispose();void this.wake?.release();}
}
