import Ajv from 'ajv';
import manifestSchema from '../../../schemas/manifest.schema.json';
import chartSchema from '../../../schemas/chart.schema.json';
import type {Manifest,Chart,SongPackage} from '../../../contracts/public-types';
const ajv=new Ajv({allErrors:true});const vm=ajv.compile(manifestSchema),vc=ajv.compile(chartSchema);
export async function sha256(bytes:Uint8Array|ArrayBuffer){const data=bytes instanceof Uint8Array?new Uint8Array(bytes).buffer:bytes;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function validateManifest(v:unknown):asserts v is Manifest {if(!vm(v))throw Error('曲情報の形式が不正です: '+ajv.errorsText(vm.errors));const m=v as unknown as Manifest;if(m.charts.some(c=>c.path!==`charts/${c.difficulty}.json`))throw Error('譜面パスと難易度が一致しません');let last=-1;for(const t of m.beatTimesMs){if(t<=last||t>=m.durationMs)throw Error('拍は曲内で厳密な昇順が必要です');last=t;}last=-1;for(const i of m.downbeatIndices){if(i<=last||i>=m.beatTimesMs.length)throw Error('小節線が不正です');last=i;}let end=0;for(const s of [...m.sections].sort((a,b)=>a.startMs-b.startMs)){if(s.startMs<end||s.endMs<=s.startMs||s.endMs>m.durationMs)throw Error('区間の重なり・長さが不正です');end=s.endMs;}if(new Set(m.charts.map(c=>c.chartId)).size!==m.charts.length||new Set(m.charts.map(c=>c.path)).size!==m.charts.length||new Set(m.charts.map(c=>c.difficulty)).size!==m.charts.length)throw Error('譜面の識別子が重複しています');}
export function validateChart(v:unknown,m:Manifest):asserts v is Chart {if(!vc(v))throw Error('譜面形式が不正です: '+ajv.errorsText(vc.errors));const c=v as unknown as Chart;const ref=m.charts.find(x=>x.chartId===c.chartId);if(!ref||ref.difficulty!==c.difficulty)throw Error('曲情報と譜面の難易度・IDが一致しません');let last=-1;const ids=new Set<string>();for(const n of c.notes){if(n.timeMs<=last||ids.has(n.id))throw Error('音符の時刻順またはIDが重複しています');last=n.timeMs;ids.add(n.id);if(n.timeMs+c.offsetMs<0||(n.kind==='roll'?n.endMs:n.timeMs)+c.offsetMs>m.durationMs)throw Error('音符が曲の範囲を超えています');if(n.kind==='roll'&&n.endMs<=n.timeMs)throw Error('連打の終了は開始より後にしてください');}const rolls=c.notes.filter(n=>n.kind==='roll');for(let i=0;i<rolls.length;i++){const r=rolls[i];if(i&&rolls[i-1].endMs>=r.timeMs)throw Error('連打が重なっています');if(c.notes.some(n=>n.kind==='tap'&&n.timeMs>=r.timeMs-90&&n.timeMs<=r.endMs+90))throw Error('通常音符と連打が近すぎます（90ms以上空けてください）');}if(!c.notes.some(n=>n.kind==='tap'))throw Error('通常音符が1つ以上必要です');}
export async function validatePackage(pack:SongPackage,decode=true){const m=pack.manifest;validateManifest(m);if(pack.charts.length!==m.charts.length)throw Error('譜面の数が一致しません');for(const c of pack.charts)validateChart(c,m);if(await sha256(await pack.audio.arrayBuffer())!==m.audio.sha256)throw Error('音源のSHA-256が一致しません');if(decode){const c=new AudioContext({sampleRate:44100});try{const b=await c.decodeAudioData(await pack.audio.arrayBuffer());if(Math.abs(b.duration*1000-m.durationMs)>100||b.numberOfChannels>2)throw Error('音源の長さ・チャンネルが曲情報と一致しません');}finally{await c.close();}}}
