import {zipSync,strToU8,strFromU8,Unzip,UnzipInflate} from 'fflate';
import type {SongPackage,Manifest,Chart} from '../../../contracts/public-types';
import {validateManifest,validateChart,sha256} from './validators';
import {blobWithBytes} from './bytes';
const MiB=1024*1024;const allowed=/^(manifest\.json|audio\/song\.(m4a|mp3|wav)|charts\/(easy|normal|hard)\.json|art\/cover\.(webp|png|jpg))$/;
export function unpack(bytes:Uint8Array){if(bytes.length>96*MiB)throw Error('ZIPは96MiBまでです');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let e=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(v.getUint32(i,true)===0x06054b50){e=i;break;}}if(e<0)throw Error('ZIP形式が不正です');const count=v.getUint16(e+10,true);if(count<2||count>16)throw Error('ZIPのファイル数が不正です');let off=v.getUint32(e+16,true),total=0;const names=new Set<string>();for(let i=0;i<count;i++){if(off+46>bytes.length||v.getUint32(off,true)!==0x02014b50)throw Error('ZIP目録が不正です');const n=v.getUint16(off+28,true),extra=v.getUint16(off+30,true),comment=v.getUint16(off+32,true);const path=strFromU8(bytes.subarray(off+46,off+46+n));const mode=v.getUint32(off+38,true)>>>16;if(!allowed.test(path)||names.has(path)||v.getUint16(off+8,true)&1||(mode&0xf000)===0xa000)throw Error('許可されていないパス・重複・暗号化・リンクです');names.add(path);const size=v.getUint32(off+24,true);const limit=path.startsWith('audio')?80*MiB:path.startsWith('charts')?8*MiB:2*MiB;if(size>limit)throw Error('ファイルの容量が上限を超えています');total+=size;off+=46+n+extra+comment;}if(total>160*MiB)throw Error('展開サイズが160MiBを超えています');
 const output:Record<string,Uint8Array>={};const localNames=new Set<string>();let actual=0;const zip=new Unzip(file=>{if(!names.has(file.name)||localNames.has(file.name))throw Error('ZIP内部パスが目録と異なります');localNames.add(file.name);const chunks:Uint8Array[]=[];let size=0;file.ondata=(err,data,final)=>{if(err)throw err;size+=data.length;actual+=data.length;if(actual>160*MiB||size>(file.name.startsWith('audio')?80*MiB:file.name.startsWith('charts')?8*MiB:2*MiB)){file.terminate();throw Error('実展開サイズが上限を超えました');}chunks.push(data);if(final){const b=new Uint8Array(size);let p=0;for(const c of chunks){b.set(c,p);p+=c.length;}output[file.name]=b;}};file.start();});zip.register(UnzipInflate);for(let i=0;i<bytes.length;i+=65536)zip.push(bytes.subarray(i,i+65536),i+65536>=bytes.length);if(Object.keys(output).length!==names.size)throw Error('ZIPが途中で途切れています');return output;
}
export async function readFiles(files:Record<string,Uint8Array>):Promise<SongPackage>{if(!files['manifest.json'])throw Error('manifest.jsonがありません');const m:unknown=JSON.parse(strFromU8(files['manifest.json']));validateManifest(m);const manifest=m as Manifest;const used=new Set(['manifest.json',manifest.audio.path,...manifest.charts.map(c=>c.path),...(manifest.cover?[manifest.cover.path]:[])]);if(Object.keys(files).some(p=>!used.has(p)))throw Error('曲情報に含まれない余分なファイルです');const a=files[m.audio.path];if(!a||await sha256(a)!==m.audio.sha256)throw Error('音源のSHA-256が一致しません');if(!(m.audio.path.endsWith('.wav')&&strFromU8(a.subarray(0,4))==='RIFF'||m.audio.path.endsWith('.m4a')&&strFromU8(a.subarray(4,8))==='ftyp'||m.audio.path.endsWith('.mp3')&&(strFromU8(a.subarray(0,3))==='ID3'||a[0]===255)))throw Error('音源のコンテナが不正です');const charts:Chart[]=[];for(const ref of m.charts){const b=files[ref.path];if(!b||await sha256(b)!==ref.sha256)throw Error('譜面のSHA-256が一致しません');const c:unknown=JSON.parse(strFromU8(b));validateChart(c,m);charts.push(c);}let cover:Blob|undefined;if(m.cover){const b=files[m.cover.path];if(!b||await sha256(b)!==m.cover.sha256)throw Error('表紙のSHA-256が一致しません');cover=new Blob([new Uint8Array(b)]);}return {manifest,charts,audio:new Blob([new Uint8Array(a)],{type:m.audio.path.endsWith('m4a')?'audio/mp4':m.audio.path.endsWith('wav')?'audio/wav':'audio/mpeg'}),cover,source:'import'};}
export async function exportPack(pack:SongPackage){const m=structuredClone(pack.manifest);const files:Record<string,Uint8Array>={};files[m.audio.path]=new Uint8Array(await pack.audio.arrayBuffer());m.audio.sha256=await sha256(files[m.audio.path]);for(const c of pack.charts){validateChart(c,m);const ref=m.charts.find(r=>r.chartId===c.chartId)!;files[ref.path]=strToU8(JSON.stringify(c));ref.sha256=await sha256(files[ref.path]);}if(pack.cover&&m.cover){files[m.cover.path]=new Uint8Array(await pack.cover.arrayBuffer());m.cover.sha256=await sha256(files[m.cover.path]);}validateManifest(m);files['manifest.json']=strToU8(JSON.stringify(m));return new Blob([new Uint8Array(zipSync(files,{level:1}))],{type:'application/zip'});}
/** Reads a ZIP (a picked File, or bytes already fetched) in a worker. */
export function importZip(source:Blob|ArrayBuffer,signal?:AbortSignal):Promise<SongPackage>{
 if((source instanceof Blob?source.size:source.byteLength)>96*MiB)return Promise.reject(Error('ZIPは96MiBまでです'));
 // Never start a worker for a request that is already cancelled.
 if(signal?.aborted)return Promise.reject(new DOMException('取込を取り消しました','AbortError'));
 return new Promise((resolve,reject)=>{
  const worker=new Worker(new URL('../workers/zip.worker.ts',import.meta.url),{type:'module'});let finished=false;
  const cleanup=()=>{finished=true;clearTimeout(timeout);worker.terminate();signal?.removeEventListener('abort',stop);};
  const fail=(error:Error)=>{if(finished)return;cleanup();reject(error);};
  const stop=()=>fail(new DOMException('取込を取り消しました','AbortError'));
  const timeout=setTimeout(()=>fail(Error('取込に時間がかかっています。ファイルを確認して再試行してください')),120000);
  signal?.addEventListener('abort',stop,{once:true});
  worker.onmessage=e=>{if(finished)return;if(e.data.error){fail(Error(e.data.error));return;}const p=e.data.pack;cleanup();resolve({manifest:p.manifest,charts:p.charts,audio:blobWithBytes(p.audioBytes,p.audioType),cover:p.coverBytes?blobWithBytes(p.coverBytes,p.coverType):undefined,source:'import'});};
  worker.onerror=e=>fail(Error(e.message));
  if(signal?.aborted)stop();else void (source instanceof Blob?source.arrayBuffer():Promise.resolve(source)).then(buffer=>{if(!finished)worker.postMessage(buffer,[buffer]);},fail);
 });
}
