import {chromium} from 'playwright';
import {mkdirSync} from 'node:fs';
mkdirSync('reports/screenshots',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
page.on('pageerror',e=>console.log('PAGEERROR',e.message));page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
await page.goto('http://127.0.0.1:5173/');await page.getByRole('link',{name:/はじめる/}).waitFor({timeout:30000});
await page.screenshot({path:'reports/screenshots/home.png'});
await page.getByRole('link',{name:/はじめる/}).click();await page.getByRole('button',{name:'この曲であそぶ　→'}).waitFor();
await page.screenshot({path:'reports/screenshots/library.png'});
await page.getByRole('button',{name:'この曲であそぶ　→'}).click();await page.getByRole('button',{name:'演奏をはじめる'}).waitFor();
await page.screenshot({path:'reports/screenshots/ready.png'});
await page.getByRole('button',{name:'演奏をはじめる'}).click();await page.waitForTimeout(3500);await page.screenshot({path:'reports/screenshots/playing.png'});
console.log(await page.locator('body').innerText());
await browser.close();
