#!/bin/zsh
# Builds "ちゃちゃまる譜面工房.app" in ~/Applications (macOS only).
# Opening the app, or a chachamaru-studio:// link from the game, opens the Mac
# Studio of this folder; it is started in the background when not running.
# Run again after moving this folder. Remove: delete the app from ~/Applications.
set -euo pipefail
repo="${0:A:h:h}"
name="ちゃちゃまる譜面工房"
app="$HOME/Applications/$name.app"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The applet stays ASCII; the folder path lives in a UTF-8 shell script it runs.
cat > "$work/studio.applescript" <<'APPLESCRIPT'
on run
	openStudio("studio")
end run

on open location theURL
	if theURL starts with "chachamaru-studio://songs" then
		openStudio("songs")
	else
		openStudio("studio")
	end if
end open location

on openStudio(route)
	set launcher to quoted form of (POSIX path of (path to resource "open-studio.sh"))
	try
		do shell script launcher & " " & route
	on error message
		display dialog message buttons {"OK"} default button "OK" with title "Chachamaru Studio" with icon caution
	end try
end openStudio
APPLESCRIPT

mkdir -p "$HOME/Applications"
rm -rf "$app"
osacompile -o "$app" "$work/studio.applescript"

cat > "$app/Contents/Resources/open-studio.sh" <<SCRIPT
#!/bin/zsh
# Generated by scripts/install-mac-app.sh for: $repo
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
cd '$repo' 2>/dev/null || { print -u2 "ちゃちゃまるのフォルダが見つかりません:\n$repo\nフォルダを移動したときは scripts/install-mac-app.sh を実行し直してください。"; exit 1; }
flag=()
[[ "\${1:-}" == songs ]] && flag=(--game)
mkdir -p _private
exec node scripts/studio.mjs --app "\${flag[@]}" >> _private/studio-app.log
SCRIPT
chmod +x "$app/Contents/Resources/open-studio.sh"

plist="$app/Contents/Info.plist"
plutil -replace CFBundleIdentifier -string io.github.kochamari.chachamaru-studio "$plist"
plutil -replace CFBundleName -string "$name" "$plist"
plutil -replace CFBundleDisplayName -string "$name" "$plist"
plutil -replace LSUIElement -bool true "$plist"
plutil -replace CFBundleURLTypes -json '[{"CFBundleURLName":"Chachamaru Studio","CFBundleURLSchemes":["chachamaru-studio"]}]' "$plist"

# Icon from the game's app icon.
iconset="$work/applet.iconset"
mkdir -p "$iconset"
for size in 16 32 128 256 512; do
	sips -z $size $size "$repo/web/public/icon-512.png" --out "$iconset/icon_${size}x${size}.png" >/dev/null
	double=$((size*2)); [[ $double -gt 512 ]] && double=512
	sips -z $double $double "$repo/web/public/icon-512.png" --out "$iconset/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$iconset" -o "$app/Contents/Resources/applet.icns"
# osacompile adds an asset catalog whose default icon would win over ours.
rm -f "$app/Contents/Resources/Assets.car"
plutil -remove CFBundleIconName "$plist" 2>/dev/null || true

codesign --force --deep --sign - "$app" >/dev/null 2>&1
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$app"
print "作成しました: $app"
