import {openDB,type IDBPDatabase} from 'idb';
import type {SongPackage,RunResult,Settings,Manifest,Chart} from '../../../contracts/public-types';
import {validSettings} from '../app/store';
let dbPromise:Promise<IDBPDatabase>|undefined;
const storedBlob=(value:Blob|{bytes:ArrayBuffer;type:string})=>value instanceof Blob?value:new Blob([value.bytes],{type:value.type});
export function db(){return dbPromise??=openDB('chachamaru-rhythm',1,{upgrade(d){d.createObjectStore('songs',{keyPath:'packId'});d.createObjectStore('blobs');d.createObjectStore('charts');d.createObjectStore('settings');d.createObjectStore('records');d.createObjectStore('runs',{keyPath:'runId'});}});}
export async function listSongs():Promise<Manifest[]>{return (await (await db()).getAll('songs')).map(x=>x.manifest);}
export async function getSong(id:string):Promise<SongPackage|null>{const d=await db(),s=await d.get('songs',id);if(!s)return null;const charts:Chart[]=[];for(const r of s.manifest.charts)charts.push(await d.get('charts',[id,r.chartId]));return {manifest:s.manifest,charts,audio:storedBlob(await d.get('blobs',s.manifest.audio.sha256)),cover:s.manifest.cover?storedBlob(await d.get('blobs',s.manifest.cover.sha256)):undefined,source:s.source};}
export async function saveSong(pack:SongPackage,mode:'check'|'replace'|'copy'='check'){const d=await db(),m=structuredClone(pack.manifest),old=await d.get('songs',m.packId);if(old&&JSON.stringify(old.manifest)===JSON.stringify(m))return 'duplicate';if(old&&mode==='check')return 'conflict';if(old&&mode==='copy'){m.packId=crypto.randomUUID();}const audioBytes=await pack.audio.arrayBuffer(),coverBytes=await pack.cover?.arrayBuffer();const tx=d.transaction(['songs','charts','blobs'],'readwrite');const writes:Promise<unknown>[]=[];try{if(old&&mode==='replace')for(const c of old.manifest.charts)writes.push(tx.objectStore('charts').delete([m.packId,c.chartId]));writes.push(tx.objectStore('songs').put({packId:m.packId,manifest:m,source:pack.source,importedAt:new Date().toISOString()}));writes.push(tx.objectStore('blobs').put({bytes:audioBytes,type:pack.audio.type},m.audio.sha256));if(m.cover&&pack.cover)writes.push(tx.objectStore('blobs').put({bytes:coverBytes,type:pack.cover.type},m.cover.sha256));for(const c of pack.charts)writes.push(tx.objectStore('charts').put(c,[m.packId,c.chartId]));await Promise.all([...writes,tx.done]);}catch(e){try{tx.abort();}catch{/* transaction already aborted */}await Promise.allSettled([...writes,tx.done]);throw e;}await collectBlobs();return 'saved';}
async function collectBlobs(){const d=await db(),tx=d.transaction(['songs','blobs'],'readwrite');const songs=await tx.objectStore('songs').getAll();const refs=new Set(songs.flatMap(s=>[s.manifest.audio.sha256,s.manifest.cover?.sha256]));for(const key of await tx.objectStore('blobs').getAllKeys())if(!refs.has(key))void tx.objectStore('blobs').delete(key);await tx.done;}
export async function deleteSong(id:string){const d=await db(),old=await d.get('songs',id);if(!old)return;const tx=d.transaction(['songs','charts'],'readwrite');void tx.objectStore('songs').delete(id);for(const c of old.manifest.charts)void tx.objectStore('charts').delete([id,c.chartId]);await tx.done;await collectBlobs();}
export const recordEligible=(r:RunResult)=>!r.autoplay&&!r.practice&&!r.timingUnstable&&r.inputMode!=='mixed';
export const recordKey=(r:RunResult)=>[r.packId,r.chartId,r.audioHash,r.chartHash,r.ruleset,r.inputMode];
export async function saveRun(r:RunResult){const d=await db();await d.put('runs',r);if(recordEligible(r)){const key=recordKey(r),prev=await d.get('records',key);if(!prev||r.stats.score>prev.stats.score)await d.put('records',r,key);}}
export async function saveSettings(settings:Settings){if(!validSettings(settings))throw Error('設定値が不正です');await (await db()).put('settings',settings,'main');}
export async function backup(){const d=await db();return {schemaVersion:1,savedAt:new Date().toISOString(),ruleset:'chacha-v1',settings:await d.get('settings','main'),records:await d.getAll('records'),runs:await d.getAll('runs')};}
function validRun(value:unknown):value is RunResult {
 if(!value||typeof value!=='object')return false;
 const r=value as RunResult,s=r.stats;
 const text=(v:unknown)=>typeof v==='string'&&v.length>0&&v.length<=200;
 if(!text(r.runId)||!text(r.packId)||!text(r.chartId)||!text(r.title)||!['easy','normal','hard'].includes(r.difficulty)||typeof r.date!=='string'||!Number.isFinite(Date.parse(r.date))||!validSettings(r.settings)||r.ruleset!=='chacha-v1'||!['touch','keyboard','midi','mixed'].includes(r.inputMode)||typeof r.audioHash!=='string'||typeof r.chartHash!=='string'||!/^[a-f0-9]{64}$/.test(r.audioHash)||!/^[a-f0-9]{64}$/.test(r.chartHash))return false;
 if(![r.autoplay,r.practice,r.timingUnstable].every(v=>typeof v==='boolean')||!s||typeof s!=='object')return false;
 const counts=[s.score,s.baseScore,s.rollBonus,s.rollHits,s.great,s.ok,s.miss,s.combo,s.maxCombo,s.resolved,s.total];
 if(!counts.every(v=>Number.isSafeInteger(v)&&v>=0)||s.baseScore>1000000||s.score!==s.baseScore+s.rollBonus||s.total>50000||s.resolved!==s.great+s.ok+s.miss||s.resolved>s.total||s.combo>s.maxCombo||s.maxCombo>s.total)return false;
 if(!Number.isFinite(s.gauge)||s.gauge<0||s.gauge>100||!Number.isFinite(s.accuracy)||s.accuracy<0||s.accuracy>1||![s.fullCombo,s.allGreat,s.timingUnstable,s.finished].every(v=>typeof v==='boolean'))return false;
 return Array.isArray(s.deltas)&&s.deltas.length<=50000&&s.deltas.every(v=>Number.isFinite(v)&&Math.abs(v)<=90);
}
export async function restore(data:unknown){if(!data||typeof data!=='object')throw Error('バックアップが不正です');const b=data as {schemaVersion:number;ruleset:string;settings:Settings;records:RunResult[];runs:RunResult[]};if(b.schemaVersion!==1||b.ruleset!=='chacha-v1'||!validSettings(b.settings)||!Array.isArray(b.records)||!Array.isArray(b.runs)||b.records.length+b.runs.length>10000)throw Error('互換性のないバックアップです');if(![...b.records,...b.runs].every(validRun))throw Error('記録データが不正です');const d=await db(),tx=d.transaction(['settings','records','runs'],'readwrite');void tx.objectStore('settings').put(b.settings,'main');for(const r of b.records)if(recordEligible(r))void tx.objectStore('records').put(r,recordKey(r));for(const r of b.runs)void tx.objectStore('runs').put(r);await tx.done;}
