import {Application,Container,Graphics,Text} from 'pixi.js';
import type {Chart,Manifest,Settings,GameSnapshot,EffectEvent,Note} from '../../../contracts/public-types';
import {Character,characterSvg} from './Character';
const INK=0x23312f,CREAM=0xfff2ce,DON=0xf35a43,KA=0x2cbbd5,GOLD=0xffd86b;
export class Renderer {
 app=new Application();private notePool:{root:Container;graphic:Graphics;label:Text;key:string}[]=[];private particles:{x:number;y:number;vx:number;vy:number;life:number;color:number}[]=[];private fx=new Graphics();private bars=new Graphics();private judgement=new Text({text:'',style:{fontFamily:'serif',fontSize:42,fontWeight:'bold',fill:GOLD,stroke:{color:INK,width:4}}});private judgementAt=-1000;private hitX=166;private W=1280;private H=720;private last=0;private resizeObs:ResizeObserver;private character:Character;private initialized=false;private chorus=false;private frameSamples:number[]=[];private slowWindows=0;private frameWindowAt=0;private frameWindowStarted=0;private upcomingIndex=0;private lastTime=-Infinity;private alive=true;private friendCount=0;
 readonly metrics={p95:0,quality:'standard'};
 constructor(private root:HTMLElement,private stage:HTMLElement,private chart:Chart,private manifest:Manifest,private settings:Settings){this.character=new Character(stage.querySelector('.character')!);this.resizeObs=new ResizeObserver(()=>this.resize());}
 async init(){await this.app.init({width:1280,height:720,backgroundAlpha:0,antialias:true,resolution:Math.min(devicePixelRatio,2),autoDensity:true,preference:'webgl'});if(!this.alive){this.app.destroy(true,{children:true});return;}this.root.prepend(this.app.canvas);this.app.canvas.className='game-canvas';this.app.stage.addChild(this.bars);for(let i=0;i<100;i++){const root=new Container(),graphic=new Graphics(),label=new Text({text:'',style:{fontFamily:'sans-serif',fontSize:14,fontWeight:'bold',fill:INK}});label.anchor.set(.5);label.y=14;root.addChild(graphic,label);this.app.stage.addChild(root);this.notePool.push({root,graphic,label,key:''});}this.app.stage.addChild(this.fx,this.judgement);this.judgement.anchor.set(.5);this.initialized=true;this.resizeObs.observe(this.root);this.resize();this.app.ticker.stop();}
 private resize(){if(!this.initialized)return;const portrait=this.root.clientHeight>this.root.clientWidth;this.W=portrait?720:720*this.root.clientWidth/this.root.clientHeight;const H=this.H=portrait?720*this.root.clientHeight/this.root.clientWidth:720;this.hitX=Math.max(132,Math.min(220,this.W*.13));this.app.renderer.resize(this.W,H);this.root.style.setProperty('--logical-width',String(this.W));this.stage.style.setProperty('--scale',String(Math.min(this.root.clientWidth/this.W,this.root.clientHeight/H)));}
 private paint(g:Graphics,n:Note){g.clear();if(n.kind==='roll')return;const color=n.color==='don'?DON:KA,r=n.size==='large'?36:27;g.moveTo(-r*.8,-r*.6).lineTo(-r*.67,-r*1.06).lineTo(-r*.22,-r*.89).fill(color).stroke({color:INK,width:3});g.moveTo(r*.8,-r*.6).lineTo(r*.67,-r*1.06).lineTo(r*.22,-r*.89).fill(color).stroke({color:INK,width:3});g.circle(0,0,r).fill(color).stroke({color:CREAM,width:4});g.circle(0,0,r+3).stroke({color:INK,width:2});g.ellipse(-9,-5,3,4).fill(INK);g.ellipse(9,-5,3,4).fill(INK);g.moveTo(-5,3).quadraticCurveTo(0,8,5,3).stroke({color:INK,width:2});}
 draw(time:number,s:GameSnapshot,events:EffectEvent[]=[]){if(!this.initialized)return;const visibleTime=time+this.settings.visualAdvanceMs,W=this.W,portrait=this.root.clientHeight>this.root.clientWidth,H=this.H,y=portrait?H*235/1280:184,hit=this.hitX,right=W-42,speed=(right-hit)/1800,dt=Math.min(40,Math.max(0,time-this.last));this.last=time;const chorus=this.settings.festival&&this.manifest.sections.some(v=>v.kind==='chorus'&&time>=v.startMs&&time<v.endMs);this.root.classList.toggle('chorus',chorus);this.root.classList.toggle('has-combo',s.combo>=100);const friends=Math.min(4,Math.floor(s.maxCombo/100));if(friends!==this.friendCount){this.friendCount=friends;this.stage.querySelector('.friends')!.innerHTML=Array.from({length:friends},()=>`<div>${characterSvg(false)}</div>`).join('');}this.bars.clear();const g=this.bars;
g.roundRect(24,portrait?H*150/1280:100,W-48,portrait?H*168/1280:168,20).fill({color:0x18272b,alpha:.97}).stroke({color:0xb68d4e,width:3});g.roundRect(29,(portrait?H*150/1280+5:105),W-58,(portrait?H*168/1280:168)-10,16).stroke({color:0xffe0a1,width:1,alpha:.35});g.rect(hit, y-45,right-hit,90).fill({color:0x36504e,alpha:.35});g.moveTo(hit,y).lineTo(right,y).stroke({color:0xc3b98d,width:1,alpha:.3});
for(const t of this.manifest.beatTimesMs){const x=hit+(t-visibleTime)*speed;if(x<hit-30)continue;if(x>right)break;g.moveTo(x,y-43).lineTo(x,y+43).stroke({color:CREAM,width:1,alpha:.12});}g.circle(hit,y,45).stroke({color:CREAM,width:5});g.circle(hit,y,36).stroke({color:0xb0b7aa,width:2,alpha:.65});g.circle(hit,y,5).fill({color:CREAM,alpha:.7});
let idx=0;if(visibleTime<this.lastTime)this.upcomingIndex=0;this.lastTime=visibleTime;while(this.upcomingIndex<this.chart.notes.length){const n=this.chart.notes[this.upcomingIndex],end=n.kind==='roll'?n.endMs:n.timeMs;if(end+this.chart.offsetMs>=visibleTime-200)break;this.upcomingIndex++;}for(let ni=this.upcomingIndex;ni<this.chart.notes.length;ni++){const n=this.chart.notes[ni];const target=n.timeMs+this.chart.offsetMs;if(target>visibleTime+1950)break;if(s.outcomes.has(n.id))continue;if(n.kind==='tap'&&target<visibleTime-200)continue;const p=this.notePool[idx++];if(!p)break;p.root.visible=true;p.root.position.set(hit+(target-visibleTime)*speed,y);if(n.kind==='roll'){p.graphic.clear();const width=Math.max(16,(n.endMs-n.timeMs)*speed);p.graphic.roundRect(0,-22,width,44,22).fill(0xf4bd43).stroke({color:CREAM,width:4});p.graphic.circle(0,0,27).fill(GOLD).stroke({color:INK,width:3});p.label.text='連';p.key='';}else{const key=n.color+n.size;if(p.key!==key){this.paint(p.graphic,n);p.key=key;}p.label.text=this.settings.noteLabels?(n.color==='don'?'ドン':'カッ'):'';}p.label.visible=this.settings.noteLabels;}for(let i=idx;i<this.notePool.length;i++)this.notePool[i].root.visible=false;
for(const e of events){if(e.kind==='combo'){this.character.react('happy',time);if((e.value??0)>=50){this.character.jump(time);for(let i=0;i<18&&this.particles.length<(this.settings.effects==='off'?0:this.settings.effects==='reduced'?40:160);i++){const a=i*Math.PI/9;this.particles.push({x:W*.38,y:portrait?H*700/1280:415,vx:Math.cos(a)*3,vy:Math.sin(a)*3-1,life:600,color:i%2?GOLD:DON});}}continue;}if(e.kind==='chorus')continue;if(e.kind==='miss')this.character.react('miss',time);this.judgement.text=e.kind==='great'?'良':e.kind==='ok'?'可':e.kind==='miss'?'不可':'連打';this.judgement.style.fill=e.kind==='great'?GOLD:e.kind==='ok'?CREAM:e.kind==='miss'?0xc6cbc7:GOLD;this.judgementAt=time;const count=this.settings.effects==='off'?0:e.kind==='great'?10:4;for(let i=0;i<count&&this.particles.length<(this.settings.effects==='reduced'?40:160);i++){const angle=i/count*Math.PI*2;this.particles.push({x:hit,y,vx:Math.cos(angle)*2,vy:Math.sin(angle)*2,life:220,color:e.kind==='miss'?0x889999:GOLD});}}
if(chorus&&!this.chorus&&this.settings.effects!=='off')for(let i=0;i<30&&this.particles.length<(this.settings.effects==='reduced'?40:160);i++){const angle=i*Math.PI/15;this.particles.push({x:W*(i<15?.68:.86),y:portrait?H*550/1280:385,vx:Math.cos(angle)*3,vy:Math.sin(angle)*3,life:600,color:i%2?GOLD:DON});}this.chorus=chorus;
this.fx.clear();for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.life-=dt;p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;if(p.life<=0){this.particles.splice(i,1);continue;}this.fx.circle(p.x,p.y,3).fill({color:p.color,alpha:Math.min(1,p.life/200)});}const age=time-this.judgementAt;this.judgement.visible=age<220&&age>=0;this.judgement.position.set(hit,y-65);if(age<220&&age>=0)this.fx.circle(hit,y,45+age*.08).stroke({color:GOLD,width:3,alpha:1-age/220});
let b=this.manifest.beatTimesMs.findIndex(t=>t>time);if(b<1)b=1;const beats=this.manifest.beatTimesMs;const beat=b-1+(time-(beats[b-1]??0))/((beats[b]??(beats[b-1]??0)+500)-(beats[b-1]??0));this.character.update(time,beat,chorus?'chorusDance':s.miss&&age<120?'miss':'idle');this.app.render();this.root.style.setProperty('--progress',`${Math.max(0,Math.min(100,time/this.manifest.durationMs*100))}%`);
const now=performance.now();if(this.frameWindowAt){this.frameSamples.push(now-this.frameWindowAt);}this.frameWindowAt=now;if(!this.frameWindowStarted)this.frameWindowStarted=now;if(now-this.frameWindowStarted>=5000){const a=[...this.frameSamples].sort((a,b)=>a-b);this.metrics.p95=a[Math.floor(a.length*.95)];if(this.metrics.p95>25)this.slowWindows++;else this.slowWindows=0;if(this.slowWindows>=3&&this.settings.effects==='standard'){this.settings.effects='reduced';this.metrics.quality='reduced';this.app.renderer.resolution=Math.min(devicePixelRatio,1.5);}this.frameSamples=[];this.frameWindowStarted=now;}this.root.style.setProperty('--logical-height',String(H));}
 hit(color:string,time:number){this.character.hit(color,time);}
 dispose(){this.alive=false;this.resizeObs.disconnect();if(this.initialized)this.app.destroy(true,{children:true});}
}
